export const FILTERS = {
  CHANGE_VISIBILITY_FILTER: 'CHANGE_VISIBILITY_FILTER', 
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
};

export const TODO = {
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    LIST_TODOS: 'LIST_TODOS'
}